export let variables = {
    gameStateToggler: document.getElementById("gameStateToggler"),
    gameStateText: document.getElementById("gameStateText"),
    headerAvatar: document.getElementById("headerAvatar"),
    substrate: document.getElementById("substrate"),
    minutes: document.getElementById("minutes"),
    seconds: document.getElementById("seconds"),
    registerWindow: document.getElementById("registerWindow"),
    registerOpen: document.getElementById("registerOpen"),
    registerInput_1: document.getElementById("registerInput_1"),
    registerInput_2: document.getElementById("registerInput_2"),
    registerInput_3: document.getElementById("registerInput_3"),
    registerIconCheck_1: document.getElementById("registerIconCheck_1"),
    registerIconCheck_2: document.getElementById("registerIconCheck_2"),
    registerIconCheck_3: document.getElementById("registerIconCheck_3"),
    registerIconErr_1: document.getElementById("registerIconErr_1"),
    registerIconErr_2: document.getElementById("registerIconErr_2"),
    registerIconErr_3: document.getElementById("registerIconErr_3"),
    registerAvatar: document.getElementById("registerAvatar"),
    registerNoAvatar: document.getElementById("registerNoAvatar"),
    registerUserAvatar: document.getElementById("registerUserAvatar"),
    registerAdd: document.getElementById("registerAdd"),
    registerCancel: document.getElementById("registerCancel"),
    gameFieldSubstrate: document.getElementById("gameFieldSubstrate"),
};
export let cards = [
    {
        imageContainer: document.getElementById("gameImage_1"),
        cover: document.getElementById("backsideCard_1"),
        imageId: null,
        succes: document.getElementById("succes1"),
        fail: document.getElementById("fail1"),
    },
    {
        imageContainer: document.getElementById("gameImage_2"),
        cover: document.getElementById("backsideCard_2"),
        imageId: null,
        succes: document.getElementById("succes2"),
        fail: document.getElementById("fail2"),
    },
    {
        imageContainer: document.getElementById("gameImage_3"),
        cover: document.getElementById("backsideCard_3"),
        imageId: null,
        succes: document.getElementById("succes3"),
        fail: document.getElementById("fail3"),
    },
    {
        imageContainer: document.getElementById("gameImage_4"),
        cover: document.getElementById("backsideCard_4"),
        imageId: null,
        succes: document.getElementById("succes4"),
        fail: document.getElementById("fail4"),
    },
    {
        imageContainer: document.getElementById("gameImage_5"),
        cover: document.getElementById("backsideCard_5"),
        imageId: null,
        succes: document.getElementById("succes5"),
        fail: document.getElementById("fail5"),
    },
    {
        imageContainer: document.getElementById("gameImage_6"),
        cover: document.getElementById("backsideCard_6"),
        imageId: null,
        succes: document.getElementById("succes6"),
        fail: document.getElementById("fail6"),
    },
    {
        imageContainer: document.getElementById("gameImage_7"),
        cover: document.getElementById("backsideCard_7"),
        imageId: null,
        succes: document.getElementById("succes7"),
        fail: document.getElementById("fail7"),
    },
    {
        imageContainer: document.getElementById("gameImage_8"),
        cover: document.getElementById("backsideCard_8"),
        imageId: null,
        succes: document.getElementById("succes8"),
        fail: document.getElementById("fail8"),
    },
    {
        imageContainer: document.getElementById("gameImage_9"),
        cover: document.getElementById("backsideCard_9"),
        imageId: null,
        succes: document.getElementById("succes9"),
        fail: document.getElementById("fail9"),
    },
    {
        imageContainer: document.getElementById("gameImage_10"),
        cover: document.getElementById("backsideCard_10"),
        imageId: null,
        succes: document.getElementById("succes10"),
        fail: document.getElementById("fail10"),
    },
    {
        imageContainer: document.getElementById("gameImage_11"),
        cover: document.getElementById("backsideCard_11"),
        imageId: null,
        succes: document.getElementById("succes11"),
        fail: document.getElementById("fail11"),
    },
    {
        imageContainer: document.getElementById("gameImage_12"),
        cover: document.getElementById("backsideCard_12"),
        imageId: null,
        succes: document.getElementById("succes12"),
        fail: document.getElementById("fail12"),
    },
];
export let images = [
    { image: `<img class="game-field__container-image" src="./assets/images/elephant.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/elephant.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/bird.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/bird.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/wolf.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/wolf.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/lion.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/lion.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/tiger.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/tiger.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/pinguin.png" />`, id: 6 },
    { image: `<img class="game-field__container-image" src="./assets/images/pinguin.png" />`, id: 6 },
];
