export let animalsEasy = [
    { image: `<img class="game-field__container-image" src="./assets/images/elephant.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/elephant.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/wolf.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/wolf.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/tiger.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/tiger.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/pinguin.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/pinguin.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/cat.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/cat.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/zebra.png" />`, id: 6 },
    { image: `<img class="game-field__container-image" src="./assets/images/zebra.png" />`, id: 6 },
];
export let animalsMedium = [
    { image: `<img class="game-field__container-image" src="./assets/images/elephant.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/elephant.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/bird.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/bird.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/wolf.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/wolf.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/lion.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/lion.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/tiger.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/tiger.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/pinguin.png" />`, id: 6 },
    { image: `<img class="game-field__container-image" src="./assets/images/pinguin.png" />`, id: 6 },
    { image: `<img class="game-field__container-image" src="./assets/images/cat.png" />`, id: 7 },
    { image: `<img class="game-field__container-image" src="./assets/images/cat.png" />`, id: 7 },
    { image: `<img class="game-field__container-image" src="./assets/images/zebra.png" />`, id: 8 },
    { image: `<img class="game-field__container-image" src="./assets/images/zebra.png" />`, id: 8 },
];
export let fruitsEasy = [
    { image: `<img class="game-field__container-image" src="./assets/images/strawberry.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/strawberry.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/cherry.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/cherry.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/blueberry.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/blueberry.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/bananas.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/bananas.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/melon.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/melon.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/watermelon.png" />`, id: 6 },
    { image: `<img class="game-field__container-image" src="./assets/images/watermelon.png" />`, id: 6 },
];
export let fruitsMedium = [
    { image: `<img class="game-field__container-image" src="./assets/images/strawberry.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/strawberry.png" />`, id: 1 },
    { image: `<img class="game-field__container-image" src="./assets/images/cherry.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/cherry.png" />`, id: 2 },
    { image: `<img class="game-field__container-image" src="./assets/images/blueberry.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/blueberry.png" />`, id: 3 },
    { image: `<img class="game-field__container-image" src="./assets/images/bananas.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/bananas.png" />`, id: 4 },
    { image: `<img class="game-field__container-image" src="./assets/images/melon.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/melon.png" />`, id: 5 },
    { image: `<img class="game-field__container-image" src="./assets/images/watermelon.png" />`, id: 6 },
    { image: `<img class="game-field__container-image" src="./assets/images/watermelon.png" />`, id: 6 },
    { image: `<img class="game-field__container-image" src="./assets/images/redcurrant.png" />`, id: 7 },
    { image: `<img class="game-field__container-image" src="./assets/images/redcurrant.png" />`, id: 7 },
    { image: `<img class="game-field__container-image" src="./assets/images/apple.png" />`, id: 8 },
    { image: `<img class="game-field__container-image" src="./assets/images/apple.png" />`, id: 8 },
];
